### PR TITLE
Make movie button

### PR DESCRIPTION
**Pull request by heberlr**
Enable movie creation in PhysiCell Studio. This feature requires ffmpeg to be installed.

### CODE REVIEW

**Comment by rheiland** [comment]
First, thanks!! I'd like to start a discussion about this. First, I did test it on my Mac. It displays a new button `Make Movie` and filename at the bottom of the Plot UI. Currently, clicking the button without ffmpeg installed will print a msg in the command line terminal. Other than that, there's no feedback about what's happening. 

* probably my biggest concern is there is no "cancel", for the inevitable case of someone thinking they can readily generate a movie from LOTS of frames. Do we know if canceling the process is possible?
* my next concern is that this feature will expose a problem/bug which I've mentioned before (but I seemed to be the only one who experienced it). That is, when `Play`ing through lots of frames of scalar-colored cells (possibly playing them multiple times), I tend to get `RecursionError: maximum recursion depth exceeded while calling a Python object`. I got the same error when making multiple movies of scalar-colored cells. I tested on the `template` project.
* feedback on progress, in general, would be nice, even if just in the terminal, e.g., "frame 1/250", etc.

On a Mac, I did a `brew install ffmpeg`, but not everyone will be using brew. We will want to provide options for installing ffmpeg on all platforms, in the Studio docs/guide.

Other thoughts?

**Comment by drbergman** [comment]
My only comment in response to @rheiland above is that I, too, have seen that recursion error. I have also seen something about semaphore objects leaked (I forget the exact wording), but I think that usually only shows up when I quit the studio. Not sure if that's related though...

**Comment by rheiland** [comment]
Seems to work on both Linux and Windows (once they install ffmpeg). But, wow, how do people put up with Windows? So my only two concerns remain: 1) is it possible to cancel the movie generation if it's taking too long, and 2) can we figure out the RecursionError. I guess in the worst case, the RecursionError will "just" crash the Studio and not complete the movie generation, but their model (.xml, etc) should remain intact.

**Comment by heberlr** [comment]
Thank you for the feedback. I have addressed all the comments except for the issue related to the recursion error. Once we fix it for the play button, we can apply the same solution to the "Make Movie" button. For now, I have added a separator line, a cancel button, and a message box to provide a warning if ffmpeg is not installed, as well as a notification after the movie is generated.

**Pull request merged**
