### PR TITLE
Plot the gradient of substrates using a check box

### PR DESCRIPTION
**Pull request by heberlr**
New Checkbox in plot tab to visualize the norm of gradient of substrates.

### CODE REVIEW

**Comment by drbergman** [comment]
Looking at the code, it seems like a nice, sleek addition. Are you able to share a couple screenshots showing the checkbox in the gui interface and the gradient norm plotted? One thing I always get nervous about is getting the axes right for gradients since there's two conventions for which dim x and y vary along. So if you have an example without symmetries, that would be great

**Comment by rheiland** [comment]
Not entirely sure what symmetries you're referring to, but here's my initial test after cloning Heber's branch. Unrelated, if you cloned my colorbars branch, I'm not sure why your colorbar isn't aligned with the plot, but can dig deeper later.
Screenshot 2024-05-15 at 6 55 21 PM
Screenshot 2024-05-15 at 6 55 34 PM

**Comment by drbergman** [comment]
Sorry. Just realized I forgot about the norm part. Ignore that comment about symmetries and dims of gradient computations. This looks good

**Comment by rheiland** [comment]
The colorbar wasn't aligned with the plot because the widgets panel had an increased width due to the added checkbox (moving the slider separating the widgets panel and plot panel will likely cause the colorbar to misalign with the plot - another annoyance perhaps). I've put the new "norm" checkbox onto the top row and now at least the colorbar is initially aligned as I'd expected. I'll probably do a custom merge of this into dev and main as I'm still reluctant to merge the more major colorbar changes until Vincent or Marco have had a chance to test with PhysiBoSS.

Screenshot 2024-05-16 at 7 03 00 AM

**Comment by rheiland** [comment]
Sigh. Probably. I'll look into it.

**Comment by heberlr** [comment]
> Sigh. Probably. I'll look into it. Did you expect to see the lower gradient norm values at the right boundary on your test above?

Yes, I generated this substrate using a half-Gaussian function without diffusion or absorption.I have another example with exponential function this is the output:
Screenshot 2024-05-16 at 8 55 16 AM
Screenshot 2024-05-16 at 8 55 31 AM

**Pull request merged**
