### PR TITLE
Warning if attack rate is too high

### PR DESCRIPTION
**Pull request by drbergman**
If attack rate > 1/mechanics_dt, then the probability of initiating an attack is > 1. This means the attack rate exceeding 1/mechanics_dt is equivalent to setting it to 1/mechanics_dt. So, rather than let users think they're making a cell type attack more aggressively, let them know that they have maxed out the attack rate and recommend they set it lower.

### CODE REVIEW

**Comment by drbergman** [comment]
Actually, I forgot to factor in immunogenicity...

**Comment by drbergman** [comment]
implemented handling for once immunogenicity is implemented. also have checks so it doesn't crash if the immunogenicity implementation ends up being changed from current commented code

**Comment by drbergman** [comment]
This is ready to merge. The updated attack module still has the same definition for `attack rate` so the same warning applies. When `immunogenicity` is added in the future, this will require a small change to the logic for selecting the validator, but will otherwise be ready to go.

**Comment by rheiland** [comment]
Thanks!

**Pull request merged**
