### PR TITLE
Solved crash when setting max time, fixed weird stretch in death tab, added bin icon to delete button.

### PR DESCRIPTION
**Pull request by marcorusc**
Hi Randy!

Three small modification:

1) I have modified the Death tab so the box which contains the transition rate and the duration no longer stretch weirdly but it remains constant when changing the window resolution.

2) Solved a bug that was causing Studio to crash when pressing the +1 day in Config Basics when setting Max Time, in case the box on the side is empty. It happened to me several times because when I want to quickly reset the max time to a different value, I usually double click on it, delete the number, and then press the button +1. With the fix it no longer crashes.

3) Added a bin icon in Cell Types tab instead of the button with written "delete". I did for the intracellular tab too, in order to save some space. Also I think it looks nice...

That's it for now, let me know what you think!

Marco

### CODE REVIEW

**Comment by rheiland** [comment]
Thanks for the bug fix with the +1 day! As to the other 2 bullets, I'm reluctant. The bin icon ("trash") is a cognitive hesitation IMO. As in, I'm not sure what this icon represents, vs. an explicit "Delete". I'm open to opinions though. If we start using icons, I'd suggest having a description while mouse hovering on it, perhaps. And if we do use icons, we should be consistent, e.g., also use it on the Microenv tab's list of substrates.
And about the alignment in the death tab, I'm wondering if it's a platform specific thing because I see no change in behavior on macOS. I've discovered that doing fixed-width widgets can introduce unwanted behaviors. Again, I'm open to it, but want the outcome to be consistent, including cross-platform, if possible.

**Review by rheiland — APPROVED** [review]

**Comment by marcorusc** [comment]
No problem!

"""
The bin icon ("trash") is a cognitive hesitation IMO. As in, I'm not sure what this icon represents, vs. an explicit "Delete". I'm open to opinions though. If we start using icons, I'd suggest having a description while mouse hovering on it, perhaps. And if we do use icons, we should be consistent, e.g., also use it on the Microenv tab's list of substrates.
"""

I agree with this, we can discuss this more later on, it is not that import, it is just a visual thing!

"""
And about the alignment in the death tab, I'm wondering if it's a platform specific thing because I see no change in behavior on macOS. I've discovered that doing fixed-width widgets can introduce unwanted behaviors.
"""
I did not tried it on different OS, on linux at least this is how it appears full screen mode:

No fix:
Capture d’écran du 2023-09-15 14-08-32

FIx:
Capture d’écran du 2023-09-15 14-06-44

Again, is not something super important, and I agree that being consistent is the priority! I will test it on different OS and I will let you know! Thanks a lot!

**Comment by vincent-noel** [comment]
We already introduced the trash icon in the intracellular PhysiBoSS tab. To me it's better because it uses less space. But then if we decide not to use it I'm ok with restoring the old button.

**Comment by rheiland** [comment]
Merged. And added trash icon to Microenv too and made both buttons shorter in width, making them less likely to be accidently clicked. Might consider using yellow background for those buttons in boolean UI too.

**Pull request merged**
